- name: Check connection from agent to webserver
  uri:
    url: "https://{{ web_ip }}/api/__healthcheck"
    timeout: 5
    validate_certs: false
  register: _result
  until: _result.status == 200
  retries: 7
  delay: 5

- name: Install agent role
  command: "bash {{ tempdir.path }}/kasm_release/install.sh -S agent -e -p {{ target_ip }} -m {{ web_ip }} -M {{ manager_token }} {{ '-s ' ~ service_images_copy.dest if service_images_file }} {{ '-w ' ~ workspace_images_copy.dest if workspace_images_file }}"
  register: install_output
  become: true
  retries: 20
  delay: 10
  until: install_output is success or ('Failed to lock apt for exclusive operation' not in install_output.stderr and '/var/lib/dpkg/lock' not in install_output.stderr)
