# Setup default creds if users don't set them in the inventory

- set_fact:
    database_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"
  when: database_password is not defined
  run_once: true
  delegate_to: localhost

- set_fact:
    redis_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"
  when: redis_password is not defined
  run_once: true
  delegate_to: localhost
  
- set_fact:
    user_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"
  when: user_password is not defined
  run_once: true
  delegate_to: localhost

- set_fact:
    admin_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"
  when: admin_password is not defined
  run_once: true
  delegate_to: localhost

- set_fact:
    manager_token: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"
  when: manager_token is not defined
  run_once: true
  delegate_to: localhost

- set_fact:
    registration_token: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=22') }}"
  when: registration_token is not defined
  run_once: true
  delegate_to: localhost 
